name: flutter_applicationtest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  intl: ^0.20.2
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  modal_progress_hud_nsn: ^0.5.1
  http: ^1.2.0
  sqflite: ^2.3.3
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  flutter_onnxruntime: ^1.5.2
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  fl_chart: ^1.1.1
  # removed tflite_flutter_helper: using raw Float32List with tflite_flutter instead

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/mamaabbys.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/mamaabbys.jpg"
