name: Flutter tests

on:
  push:
    branches: [ main, vahn ]
  pull_request:
    branches: [ main, vahn ]

jobs:
  test:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test -r expanded
